#+TITLE: Hello, world!
#+DATE_CREATED: [2020-05-15]
#+DATE_UPDATED: [2021-01-21]

UPDATE: This is no longer true. TODO write a post explaining what is true now!

This thing is made using [[https://svelte.dev/][svelte]] and [[https://sapper.svelte.dev/][sapper]]. It starts from the [[https://github.com/sveltejs/sapper-template][sapper template]] and steals a bunch of things from [[https://github.com/22mahmoud/mahmoudashraf.dev][this GitHub repo]]. It's pretty bare-bones for now, but I really just wanted something simple where I could understand all the parts. The theme is based on [[https://draculatheme.com/][Dracula]], which I use for everything possible.

I don't really do anything to do with web programming at all, so this is all pretty new to me. However, I'm working on a web project with some friends that uses these technologies, so figured I'd better learn something about how they work.

I'm planning to write random ramblings about all kinds of things. Programming mostly, since that's what I do for work, and I'm always learning things which current me wishes past me wrote down somewhere. But also maybe knitting, linguistics, [[https://www.instagram.com/malmandlack/][guinea pigs]] and sketchnotes. Or some crazy mashup of them all, who knows.

Expect the writing to be rough and somewhat stream of consciousness - I'm aiming to capture thought processes and learnings rather than write a novel.
