name: Firn

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download firn
        run: curl -s https://raw.githubusercontent.com/theiceshelf/firn/master/install -o install-firn
      - name: Install firn
        run: chmod +x install-firn && sudo ./install-firn
      - name: Build with firn
        run: firn build -d /home/runner/work/caro401.github.io/caro401.github.io/src
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/_firn/_site
          exclude_assets: '.github,**/.gitignore'